### ISSUE TITLE
Add Project 3 Scheduling Autograder to Gradescope

### ISSUE THREAD

**Issue by timdrichards** [umass-cs-377/umass-cs-377.github.io#84]
The Project 3 Scheduler Autograder needs to be added to Gradescope.

@nightdawnex, thank you for pushing the documentation for Project to the website. Very much appreciated.

**Comment by nightdawnex** [comment]
I believe it is on there already.

**Comment by timdrichards** [comment]
Oops! Thanks - I should have looked first!
